### ISSUE TITLE
Exception thrown when decoding animated WEBP images

### ISSUE THREAD

**Issue by gsemac** [gsemac/Gsemac.Common#6]
An exception is thrown by the decoder when attempting to decode animated WEBP images:
```csharp
System.Exception: Can´t encode WebP
In WebP.Decode
   at WebPWrapper.WebP.Decode(Byte[] rawWebP)
   at Gsemac.Drawing.Imaging.WebPImageCodec.DecodeWebPBitmap(Stream stream)
   at Gsemac.Drawing.Imaging.WebPImageCodec.Decode(Stream stream)
   at Gsemac.Drawing.ImageFactoryBase.FromStream(Stream stream, IFileFormat imageFormat)
   at Gsemac.Drawing.Extensions.ImageFactoryExtensions.FromFile(IImageFactory imageFactory, String filePath)
```
This issue is noted in [WebP-wrapper](https://github.com/JosePineiro/WebP-wrapper)'s issue tracker: JosePineiro/WebP-wrapper#27 

According to the developer it's already been fixed, so recompiling `WebPWrapper.dll` with the latest source should resolve the problem.

**Comment by gsemac** [comment]
Resolved with commit 62071c9feddb85cdfd5caa340da1af9c52d2b3c7.
